In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[10,11,12],[13,14,15],[16,17,18]],
               [[19,20,21],[22,23,24],[25,26,27]]])

In [4]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],
 
        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]]))

In [6]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [7]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [8]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 3, 3), 3, dtype('int64'), 27, numpy.ndarray)

In [9]:
import pandas as pd
df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

In [10]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
np.random.randint(0,10,size=(7,2))

array([[3, 7],
       [4, 7],
       [8, 5],
       [5, 3],
       [8, 2],
       [1, 4],
       [2, 0]])

In [14]:
np.random.random(size=(3,5))

array([[0.98403134, 0.59888683, 0.08138582, 0.68478908, 0.41078236],
       [0.68281244, 0.98965846, 0.88676424, 0.4885857 , 0.5304261 ],
       [0.00431386, 0.27034999, 0.94182684, 0.86008858, 0.45336053]])

In [16]:
np.random.seed(42)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [17]:
random_array = np.random.randint(1,10,(3,7))
random_array

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [18]:
np.unique(random_array)

array([1, 2, 3, 4, 5, 7, 9])

In [20]:
random_array[:2,:]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [23]:
random_array[:1,:2]

array([[9, 1]])

In [24]:
random_array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [25]:
rand1 = np.random.randint(0,10,(3,5))
ones = np.ones((3,5))
rand1, ones

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [35]:
rand1 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [36]:
ones_2 = np.ones((5,3))
ones_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
rand1 + ones_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [38]:
ones_3 = np.ones((3,5))

In [39]:
ones_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
rand1 

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [41]:
rand1 - ones_3

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [42]:
rand1 * ones_3

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [43]:
rand1**2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [44]:
np.square(rand1)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [46]:
np.mean(rand1)

np.float64(3.8666666666666667)

In [47]:
np.max(rand1)

np.int64(9)

In [48]:
np.min(rand1)

np.int64(0)

In [49]:
rand1.std()

np.float64(2.578543947441829)

In [50]:
rand1.var()

np.float64(6.648888888888889)

In [52]:
rand1, rand1.shape

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 (3, 5))

In [55]:
rand1 = rand1.reshape(3,5,1)
rand1

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [56]:
rand1.T

array([[[6, 1, 5],
        [7, 7, 9],
        [2, 3, 3],
        [0, 1, 5],
        [3, 5, 1]]])

In [57]:
r1 = np.random.randint(0,10,(2,3))
r2 = np.random.randint(0,10,(3,2))
r1,r2

(array([[9, 8, 6],
        [8, 7, 1]]),
 array([[0, 6],
        [6, 7],
        [4, 2]]))

In [58]:
np.dot(r1,r2)

array([[ 72, 122],
       [ 46,  99]])

In [59]:
r3 = np.random.randint(0,10,(4,3))
r4 = np.random.randint(0,10,(4,3))
r3, r4

(array([[7, 5, 2],
        [0, 2, 4],
        [2, 0, 4],
        [9, 6, 6]]),
 array([[8, 9, 9],
        [2, 6, 0],
        [3, 3, 4],
        [6, 6, 3]]))

In [60]:
np.dot(r3,r4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [61]:
np.dot(r3,r4.T)

array([[119,  44,  44,  78],
       [ 54,  12,  22,  24],
       [ 52,   4,  22,  24],
       [180,  54,  69, 108]])

In [62]:
r5 = np.random.randint(0,10,(4,3))
r6 = np.random.randint(0,10,(4,3))
r5, r6

(array([[6, 2, 5],
        [1, 9, 8],
        [4, 5, 3],
        [9, 6, 8]]),
 array([[6, 0, 0],
        [8, 8, 3],
        [8, 2, 6],
        [5, 7, 8]]))

In [63]:
r5 > r6, r5 >= r6 

(array([[False,  True,  True],
        [False,  True,  True],
        [False,  True, False],
        [ True, False, False]]),
 array([[ True,  True,  True],
        [False,  True,  True],
        [False,  True, False],
        [ True, False,  True]]))

In [64]:
r5 > 7

array([[False, False, False],
       [False,  True,  True],
       [False, False, False],
       [ True, False,  True]])

In [65]:
r5 == 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [66]:
np.sort(r5)

array([[2, 5, 6],
       [1, 8, 9],
       [3, 4, 5],
       [6, 8, 9]])

In [67]:
np.argsort(r5)

array([[1, 2, 0],
       [0, 2, 1],
       [2, 0, 1],
       [1, 2, 0]])

In [68]:
np.argmax(r5), np.argmin(r5)

(np.int64(4), np.int64(3))

In [70]:
r5

array([[6, 2, 5],
       [1, 9, 8],
       [4, 5, 3],
       [9, 6, 8]])

In [69]:
np.argmax(r5, axis=1), np.argmin(r5,axis=0)

(array([0, 1, 1, 0]), array([1, 0, 2]))

In [71]:
np.random.default_rng().normal()

-1.1245291222865268

In [72]:
np.random.normal(loc=0, scale=1, size=(3, 4))

array([[ 1.94511561, -0.15333646, -0.90698723, -0.81735416],
       [-0.48312268, -0.56982835, -2.09159967,  1.26374053],
       [-0.01548334, -0.02737645,  0.81787351, -1.05460447]])

In [73]:
np.random.normal(loc=0, scale=1, size=(3, 4)).mean()

np.float64(0.3774609050749876)

In [76]:
np.linspace(1,100,10) # 10 Evenly spaced numbers 

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])