In [1]:
import pandas as pd
import numpy as np

## Datatypes and Attributes

In [2]:
# The main data type in numpy is the ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [ ]:
a2 = np.array([[1,2.0,3.3], # Matrix 2 X 3
               [4,5,6.5]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[10,11,12],[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a4 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[10,11,12],[13,14,15],[16,17,18]],
               [[19,20,21],[22,23,24],[25,26,27]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [13]:
a4.shape

(3, 3, 3)

In [14]:
a4.ndim

3

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
d2 = pd.DataFrame(a2)
d2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [18]:
d3 = pd.DataFrame(a3)
d3

ValueError: Must pass 2-d input. shape=(2, 3, 3)

## 2. Creating Arrays 

In [23]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [33]:
random_array = np.random.random((2,3)) # gives random array with values b/w 0 and 1
random_array

array([[0.89682916, 0.24522926, 0.14407795],
       [0.07347877, 0.7411974 , 0.41977283]])

In [ ]:
random_int_array = np.random.randint(1,10,(2,3)) # low, high and shape
random_int_array

array([[4, 4, 2],
       [1, 5, 4]])

In [38]:
rand_array = np.random.randint(0,10,(2,3,3))

In [39]:
rand_array

array([[[0, 1, 4],
        [2, 9, 9],
        [1, 0, 9]],

       [[3, 8, 1],
        [6, 2, 4],
        [6, 0, 9]]])

## Pseudo Random numbers and Seeding

In [49]:
np.random.seed(2) # The seed will ask np to create same random number arrays
np.random.random((2,3))

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

In [50]:
np.random.seed(2) # Wherever seed is 2 this same ndarray will be generated. 
np.random.random((2,4))

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097]])

## Viewing Arrays and Matrices

In [51]:
random_int_array

array([[4, 4, 2],
       [1, 5, 4]])

In [52]:
# Returning the Unique elements of an array
np.unique(random_int_array)

array([1, 2, 4, 5])

In [53]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [55]:
a5 = np.random.randint(10,size=(2,3,4,5))
a5

array([[[[4, 2, 4, 1, 7],
         [8, 2, 9, 8, 7],
         [1, 6, 8, 5, 9],
         [9, 9, 3, 0, 0]],

        [[2, 8, 8, 2, 9],
         [6, 5, 6, 6, 6],
         [3, 8, 2, 1, 4],
         [8, 1, 6, 9, 5]],

        [[1, 2, 4, 7, 6],
         [4, 5, 8, 3, 0],
         [0, 5, 7, 5, 0],
         [8, 6, 5, 1, 7]]],


       [[[4, 3, 6, 1, 4],
         [0, 8, 5, 4, 2],
         [9, 7, 1, 9, 2],
         [1, 0, 7, 1, 8]],

        [[9, 0, 7, 0, 5],
         [2, 5, 1, 3, 3],
         [1, 8, 6, 8, 1],
         [5, 7, 0, 9, 1]],

        [[5, 9, 2, 0, 0],
         [4, 6, 3, 1, 8],
         [5, 9, 5, 4, 2],
         [7, 8, 7, 3, 4]]]])

In [65]:
a5[:2,:2,:2,:5]

array([[[[4, 2, 4, 1, 7],
         [8, 2, 9, 8, 7]],

        [[2, 8, 8, 2, 9],
         [6, 5, 6, 6, 6]]],


       [[[4, 3, 6, 1, 4],
         [0, 8, 5, 4, 2]],

        [[9, 0, 7, 0, 5],
         [2, 5, 1, 3, 3]]]])

## 4. Manipulating and Comparing Arrays

### Arithmetic

In [66]:
a1

array([1, 2, 3])

In [67]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [68]:
a1 + ones

array([2., 3., 4.])

In [69]:
a1 - ones

array([0., 1., 2.])

In [70]:
a1 * ones

array([1., 2., 3.])

In [71]:
a1 / ones

array([1., 2., 3.])

In [72]:
a2, a3

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [73]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

## Aggregation

In [75]:
a1

array([1, 2, 3])

In [76]:
a1.sum()

np.int64(6)